version : '3'

services:

  mariadb :
    build : ./requirements/mariadb
    container_name : mariadb
    image : mariadb
    restart : on-failure
    env_file :
      - .env
    volumes :
      - DB:/var/lib/mysql
    networks :
      - myNetwork

  # cadvisor :
  #   build : ./requirements/bonus/cadvisor
  #   container_name : cadvisor
  #   image : cadvisor
  #   restart : on-failure
  #   ports :
  #     - 4000:4000
  #   volumes:
  #     - "/:/rootfs:ro"
  #     - "/var/run:/var/run:ro"
  #     - "/sys:/sys:ro
  #     - "/var/lib/docker/:/var/lib/docker:ro"
  #   networks :
  #     - myNetwork

  nginx :
    build : ./requirements/nginx
    container_name : nginx
    image : nginx
    restart : on-failure
    ports :
      - 443:443
    volumes :
      - wp:/var/www/html
    networks :
      - myNetwork
    depends_on :
      - wordpress

  wordpress :
    build : ./requirements/wordpress
    container_name : wordpress
    image : wordpress
    restart : on-failure
    volumes :
      - wp:/var/www/html
    env_file :
      - .env
    networks :
      - myNetwork
    depends_on :
      - mariadb
      # - redis

  # redis :
  #   build : ./requirements/bonus/redis
  #   container_name : redis
  #   image : redis
  #   restart : on-failure
  #   ports :
  #     - 6379:6379
  #   networks :
  #     - myNetwork

  # ftp :
  #   build : ./requirements/bonus/ftp
  #   container_name : ftp
  #   image : ftp
  #   restart : on-failure
  #   ports :
  #     - 21:21
  #     - 20:20
  #     - 40000-40005:40000-40005
  #   networks :
  #     - myNetwork
  #   volumes :
  #     - wp:/home/mechane/
  #   depends_on :
  #     - wordpress

  # adminer :
  #   build : ./requirements/bonus/adminer
  #   container_name : adminer
  #   image : adminer
  #   restart : on-failure
  #   ports :
  #     - 8080:8080
  #   networks :
  #     - myNetwork
  #   depends_on :
  #     - mariadb

  staticwebiste :
    build : ./requirements/bonus/static_website
    container_name : static_website
    restart : on-failure
    ports :
      - 81:81
    networks :
      - myNetwork

volumes :
  DB :
    driver_opts :
      type : 'none'
      o : bind
      device : /home/mechane/data/mysql
  wp :
    driver_opts :
      type : 'none'
      o : bind
      device : /home/mechane/data/wordpress

networks :
    myNetwork:
      driver: bridge