version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: unless-stopped

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_HOST: ${DB_HOST}
        URL: ${URL}
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ROLE: ${ROLE}
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        USER_EMAIL: ${USER_EMAIL}
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    env_file:
      - .env

  redis:
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: unless-stopped

  vsftpd:
    build:
      context: ./requirements/bonus/vsftpd
      dockerfile: Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    container_name: vsftpd
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env

  adminer:
    build:
      context: .
      dockerfile: requirements/bonus/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: unless-stopped

  portainer:
    build:
      context: .
      dockerfile: requirements/bonus/portainer/Dockerfile
    container_name: portainer
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: on-failure
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  website:
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    container_name: website
    ports:
      - "80:80"
    networks:
      - inception
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/mechane/data//wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/mechane/data/mariadb

  portainer_data:
    driver_opts:
      o: bind
      type: none
      device: /home/mechane/data/portainer
networks:
    inception:
        driver: bridge