CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE}\`;
CREATE USER  \`$DB_USER}\`@'localhost' IDENTIFIED BY '$DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`$DB_DATABASE}\`.* TO \`$DB_USER}\`@'%' IDENTIFIED BY '$DB_PASSWORD}';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD}';
FLUSH PRIVILEGES;
